[2023-12-11 08:04:23,054] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.crear_tabla_postgres scheduled__2023-12-04T00:00:00+00:00 [queued]>
[2023-12-11 08:04:23,135] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_con_conexion_postgres.crear_tabla_postgres scheduled__2023-12-04T00:00:00+00:00 [queued]>
[2023-12-11 08:04:23,146] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-11 08:04:23,150] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2023-12-11 08:04:23,163] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-11 08:04:23,307] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): crear_tabla_postgres> on 2023-12-04 00:00:00+00:00
[2023-12-11 08:04:23,334] {standard_task_runner.py:52} INFO - Started process 947 to run task
[2023-12-11 08:04:23,352] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_con_conexion_postgres', 'crear_tabla_postgres', 'scheduled__2023-12-04T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres_database.py', '--cfg-path', '/tmp/tmpfukzl84c', '--error-file', '/tmp/tmpmaqe03hm']
[2023-12-11 08:04:23,358] {standard_task_runner.py:80} INFO - Job 80: Subtask crear_tabla_postgres
[2023-12-11 08:04:23,793] {task_command.py:371} INFO - Running <TaskInstance: dag_con_conexion_postgres.crear_tabla_postgres scheduled__2023-12-04T00:00:00+00:00 [running]> on host 03477fa6e3b6
[2023-12-11 08:04:24,239] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=dag_con_conexion_postgres
AIRFLOW_CTX_TASK_ID=crear_tabla_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-12-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-04T00:00:00+00:00
[2023-12-11 08:04:24,311] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-11 08:04:24,616] {dbapi.py:231} INFO - Running statement: 
            create table if not exists fin_mundo(
                dt date,
                pais varchar(30)
            )
        , parameters: None
[2023-12-11 08:04:24,858] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: llave duplicada viola restricción de unicidad «pg_type_typname_nsp_index»
DETAIL:  Ya existe la llave (typname, typnamespace)=(fin_mundo, 2200).

[2023-12-11 08:04:24,927] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_con_conexion_postgres, task_id=crear_tabla_postgres, execution_date=20231204T000000, start_date=20231211T080423, end_date=20231211T080424
[2023-12-11 08:04:24,988] {standard_task_runner.py:97} ERROR - Failed to execute job 80 for task crear_tabla_postgres (llave duplicada viola restricción de unicidad «pg_type_typname_nsp_index»
DETAIL:  Ya existe la llave (typname, typnamespace)=(fin_mundo, 2200).
; 947)
[2023-12-11 08:04:25,060] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-11 08:04:25,602] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
