[2023-12-12 03:21:55,237] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Entregable3_Chumbita.cargar_data manual__2023-12-12T02:56:17.234084+00:00 [queued]>
[2023-12-12 03:21:55,252] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Entregable3_Chumbita.cargar_data manual__2023-12-12T02:56:17.234084+00:00 [queued]>
[2023-12-12 03:21:55,253] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-12 03:21:55,255] {taskinstance.py:1377} INFO - Starting attempt 6 of 6
[2023-12-12 03:21:55,256] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-12 03:21:55,285] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cargar_data> on 2023-12-12 02:56:17.234084+00:00
[2023-12-12 03:21:55,294] {standard_task_runner.py:52} INFO - Started process 2206 to run task
[2023-12-12 03:21:55,300] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Entregable3_Chumbita', 'cargar_data', 'manual__2023-12-12T02:56:17.234084+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Entregable3_Chumbita.py', '--cfg-path', '/tmp/tmpfqlg7hx6', '--error-file', '/tmp/tmpqp4he5fc']
[2023-12-12 03:21:55,302] {standard_task_runner.py:80} INFO - Job 37: Subtask cargar_data
[2023-12-12 03:21:55,405] {task_command.py:371} INFO - Running <TaskInstance: Entregable3_Chumbita.cargar_data manual__2023-12-12T02:56:17.234084+00:00 [running]> on host 02fb1b542166
[2023-12-12 03:21:55,474] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-12-12 03:21:55,534] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ArielChumbita
AIRFLOW_CTX_DAG_ID=Entregable3_Chumbita
AIRFLOW_CTX_TASK_ID=cargar_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-12T02:56:17.234084+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-12T02:56:17.234084+00:00
[2023-12-12 03:21:55,536] {logging_mixin.py:115} INFO - Cargando la data para la fecha: 2023-12-12 2
[2023-12-12 03:21:55,560] {logging_mixin.py:115} INFO - (5, 18)
[2023-12-12 03:21:55,596] {logging_mixin.py:115} INFO -    mining_algo  ...                            Date
0      SHA-256  ...  2023-12-12T02:24:25.073783104Z
1  mining_algo  ...                            Date
2      SHA-256  ...  2023-12-12T02:25:08.680354225Z
3  mining_algo  ...                            Date
4      SHA-256  ...  2023-12-12T02:56:21.454209919Z

[5 rows x 18 columns]
[2023-12-12 03:21:57,507] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_Entregable3_Chumbita.py", line 141, in cargar_data
    execute_values(cur, insert_sql, values)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/extras.py", line 1270, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: "available_on_nicehash_percent"

[2023-12-12 03:21:57,527] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Entregable3_Chumbita, task_id=cargar_data, execution_date=20231212T025617, start_date=20231212T032155, end_date=20231212T032157
[2023-12-12 03:21:57,548] {standard_task_runner.py:97} ERROR - Failed to execute job 37 for task cargar_data (invalid input syntax for type double precision: "available_on_nicehash_percent"
; 2206)
[2023-12-12 03:21:57,566] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-12-12 03:21:57,624] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
